### ISSUE TITLE
Package versions not found

### ISSUE THREAD

**Issue by samim91** [eiriniar/gleason_CNN#2]
I wanted to reproduce the results, however, I could not find any information about the versions of the packages used.
In /cnn_finetune I found the readme, which said TensorFlow 1.2.1 and Keras 2.0.5, but Keras did only have MobileNet included as a pretrained network in >2.1.5.

Looking forward to a required packages list with the used versions.

Thanks

**Comment by eiriniar** [comment]
Hi, the versions used were Tensorflow 1.1.0 and Keras 2.1.1 (the /cnn_finetune scripts were only used to train DenseNet, since at that point it was not included in Keras applications).
